site_name: Learn Kubernetes

docs_dir: labs

theme:
  name: material
  palette:
    primary: 'blue grey'
    accent: 'blue grey'
  logo:
    icon: 'chrome_reader_mode'

markdown_extensions:
    - toc:
        permalink: true
    - admonition:
    - markdown_newtab:
    - codehilite:
        linenums: true

nav:
- Home: 'index.md'
- Setup: 'setup.md'
- Namespaces: 'namespaces.md'
- Pods: 'pods.md'
- Services: 'services.md'
- ReplicaSets: 'replicasets.md'
- Deployments: 'deployments.md'
