site_name: Learn Kubernetes

docs_dir: labs

theme:
  name: material
  palette:
    primary: 'blue grey'
    accent: 'blue grey'
  logo:
    icon: 'chrome_reader_mode'

markdown_extensions:
    - toc:
        permalink: true
    - admonition:
    - markdown_newtab:
    - codehilite:
        linenums: true

pages:
- Home: 'index.md'
- Setup: '0-setup.md'
- Namespaces: '1-namespaces.md'
- Pods: '2-pods.md'
- Services: '3-services.md'
- Replicas: '4-replicas.md'
- Deployments: '5-deployments.md'
