site_name: Learn Kubernetes

docs_dir: labs

theme:
  name: material
  palette:
    primary: 'indigo'
    accent: 'indigo'
  logo:
    icon: 'class'

markdown_extensions:
    - toc:
        permalink: true
    - admonition:
    - codehilite:
        linenums: true

nav:
- Home: index.md
- Setup: setup.md
- Deploying Declaratively: deploying-declaratively.md
- Reconciliation Loop Testing: reconciliation-loop-testing.md
- Namespaces: namespaces.md
- Pods: pods.md
- ConfigMaps: configmaps.md
- Secrets: secrets.md
- Services: services.md
- ReplicaSets: replicasets.md
- Deployments: deployments.md
