apiVersion: apps/v1
kind: Deployment
metadata:
  name: cats
  labels:
    app: cats
spec:
  replicas: $REPLICAS
  selector:
    matchLabels:
      app: cats
  minReadySeconds: 30
  progressDeadlineSeconds: 600
  revisionHistoryLimit: 10
  strategy:
    rollingUpdate:
      maxUnavailable: 0%
      maxSurge: 100%
  template:
    metadata:
      name: cats
      labels:
        app: cats
      annotations:
        kubernetes.io/change-cause: $CHANGE
        checksum.api.io/configmap-app: 4028b1207b09641310193a85f85b42d1f9ee51673fd3824d43c39df1e03fa441
    spec:      
      containers:
      - name: cats
        imagePullPolicy: IfNotPresent
        image: ryanblunden/cats:$TAG

        ports:
          - name: app
            containerPort: 5000

        envFrom:
         - configMapRef:
             name: app

        resources:
          requests:
            memory: "20Mi"
            cpu: "250m"
          limits:
            memory: "50Mi"
            cpu: "500m"

        # Liveness Check: Is your application alive?
        livenessProbe:
          httpGet:
            path: /healthz
            port: app
          initialDelaySeconds: 5
          timeoutSeconds: 3
          periodSeconds: 5
          failureThreshold: 3
        
        securityContext:
          runAsNonRoot: true
          readOnlyRootFilesystem: true

      automountServiceAccountToken: false
