kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: learn-k8s
  name: deployment-manager
rules:
- apiGroups: 
  - ''
  - apps
  resources:
    - deployments
    - replicasets
    - pods

  verbs:
    - get
    - list
    - watch
    - create
    - update
    - patch
    - delete
