kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: deployment-manager-binding
  namespace: learn-k8s
subjects:
- kind: User
  name: learn-k8s
  apiGroup: ""
roleRef:
  kind: Role
  name: deployment-manager
  apiGroup: ""
