apiVersion: v1
kind: ServiceAccount
metadata:
  name: learn-k8s-user
  namespace: learn-k8s
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: namespace-manager
  namespace: learn-k8s
rules:
- apiGroups: ['', 'extensions', 'apps']
  resources: ['*']
  verbs: ['*']
- apiGroups: ['batch']
  resources:
  - jobs
  - cronjobs
  verbs: ['*']
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: learn-k8s-user-view
  namespace: learn-k8s
subjects:
- kind: ServiceAccount
  name: learn-k8s-user
  namespace: learn-k8s
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: namespace-manager
