apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: kuard-replicaset
  labels:
    app: simple-server
spec:
  replicas: 5
  selector:
    matchLabels:
      app: kuard
  template:
    metadata:
      name: api
      labels:
        app: kuard
    spec:
      containers:
      - name: simple-server
        imagePullPolicy: IfNotPresent
        image: rabbitbird/simple-server:1.0
        ports:
          - name: app
            containerPort: 8080

        #
        # Readiness Check
        #
        # Perhaps the API, while technically healthy, is not yet "ready" to receive
        # traffic, as it may be downloading data, doing computations etc.
        readinessProbe:
          httpGet:
            path: /api/v1/readiness-check/
            port: app
          initialDelaySeconds: 5
          periodSeconds: 5
        #
        # Health Check
        #
        livenessProbe:
          httpGet:
            path: /api/v1/health-check/
            port: app
          initialDelaySeconds: 5
          timeoutSeconds: 1
          periodSeconds: 10
          failureThreshold: 3
