get-iam-authenticator:
	wget curl -LO https://amazon-eks.s3-us-west-2.amazonaws.com/1.10.3/2018-07-26/bin/darwin/amd64/aws-iam-authenticator && \
		chmod +s ./aws-iam-authenticator && \
		sudo mv ./kubectl /usr/local/bin/kubectl
