apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  selector:
    app: api
  ports:
  - name: app-port
    port: 80
    targetPort: 9376
  - name: secure-app-port
    port: 443
    targetPort: 9377
  type: LoadBalancer
