apiVersion: apps/v1beta2
kind: ReplicaSet
metadata:
  name: api-replicaset
  labels:
    app: training-api
spec:
  replicas: 10
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      name: api
      labels:
        app: api
    spec:
      containers:
      - name: training-api
        imagePullPolicy: IfNotPresent
        image: training.io/api:2.0
        ports:
          - containerPort: 80
        livenessProbe: 
          httpGet: 
            path: /api/v1/health-check/
            port: 80 
          initialDelaySeconds: 5 
          timeoutSeconds: 1 
          periodSeconds: 10 
          failureThreshold: 3
