apiVersion: v1  
kind: Service  
metadata:  
  name: api-service
  namespace: default
spec:  
  selector:
    app: api-pod
  ports:
  - name: app-port
    port: 8080
    nodePort: 30005  
  type: NodePort
