apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  labels:
    app: api
spec:
  replicas: 5
  selector:
    matchLabels:
      app: api
  minReadySeconds: 30
  progressDeadlineSeconds: 600
  revisionHistoryLimit: 2
  strategy:
    rollingUpdate:
      maxUnavailable: 0%
      maxSurge: 100%
  template:
    metadata:
      name: api
      labels:
        app: api
      annotations:
        kubernetes.io/change-cause: 'Data changed in API, updating to 1.0'
    spec:
      containers:
      - name: hermetic-api
        imagePullPolicy: IfNotPresent
        image: rabbitbird/hermetic-api:1.0
        ports:
          - containerPort: 80
        livenessProbe:
          httpGet:
            path: /api/v1/health-check/
            port: 80
          initialDelaySeconds: 5
          timeoutSeconds: 1
          periodSeconds: 10
          failureThreshold: 3

# ToDO: Research how Kubernetes ensures that any previous connections are finished before killing the Pod.
# TODo: Add instructions to lab for creating different version of