apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: api-replicaset
  labels:
    app: training-api
spec:
  replicas: 5
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      name: api
      labels:
        app: api
    spec:
      containers:
      - name: training-api
        imagePullPolicy: IfNotPresent
        image: training.io/api:1.0
        ports:
          - containerPort: 80
          - containerPort: 443
        livenessProbe:
          httpGet:
            path: /api/v1/health-check/
            port: 80
          initialDelaySeconds: 5
          timeoutSeconds: 1
          periodSeconds: 10
          failureThreshold: 3
