apiVersion: v1
kind: Pod
metadata:
  name: api-pod
  labels:
    app: api
spec:
  containers:
  - name: simple-server
    imagePullPolicy: IfNotPresent
    image: rabbitbird/simple-server:1.0
    ports:
      - name: app
        containerPort: 8080
    resources:
      requests:
        memory: "200Mi"
        cpu: "250m"
      limits:
        memory: "200Mi"
        cpu: "500m"


    #
    # Readiness Check
    #
    # Perhaps the API, while technically healthy, is not yet "ready" to receive
    # traffic, as it may be downloading data, doing computations etc.
    readinessProbe:
      httpGet:
        path: /readiness-check
        port: app
      initialDelaySeconds: 5
      periodSeconds: 5
    #
    # Health Check
    #
    livenessProbe:
      httpGet:
        path: /health-check
        port: app
      initialDelaySeconds: 5
      timeoutSeconds: 1
      periodSeconds: 10
      failureThreshold: 3
