apiVersion: v1
kind: Pod
metadata:
  name: api-pod  
  labels:
    app: api
spec:
  containers:
  - name: training-api
    imagePullPolicy: IfNotPresent # So it will use local image if found, good for development
    image: training.io/api:1.0
    ports:
      - containerPort: 80
    livenessProbe: 
      httpGet: 
        path: /api/v1/health-check/
        port: 80 
      initialDelaySeconds: 5 
      timeoutSeconds: 1 
      periodSeconds: 10 
      failureThreshold: 3
