apiVersion: v1
kind: Pod
metadata:
  name: api-pod
  labels:
    app: api
spec:
  containers:
  - name: simple-server
    imagePullPolicy: IfNotPresent
    image: rabbitbird/simple-server:1.0
    ports:
      - name: app
        containerPort: 8080
    resources:
      requests:
        memory: "200Mi"
        cpu: "250m"
      limits:
        memory: "200Mi"
        cpu: "500m"


    #
    # Readiness Check: Is your app ready to serve traffic
    # 
    readinessProbe:
      httpGet:
        path: /health-check
        port: app
      initialDelaySeconds: 5
      timeoutSeconds: 1
      periodSeconds: 3
      failureThreshold: 5

    #
    # Liveness Check: Is your application even alive
    # 
    # If the process in your Container is able to crash on its own whenever 
    # it encounters an issue or becomes unhealthy, you do not necessarily need 
    # a liveness probe.
    #
    # We don't implement one because our server application *can* crash.

