apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: api-deployment
  labels:
    app: api
spec:
  replicas: 5
  selector:
    matchLabels:
      app: api  
  minReadySeconds: 60
  progressDeadlineSeconds: 600
  revisionHistoryLimit: 2
  strategy:
    rollingUpdate:
      maxUnavailable: 15%
      maxSurge: 100%
  template:
    metadata:
      name: api
      labels:
        app: api
    spec:
      containers:
      - name: training-api
        imagePullPolicy: IfNotPresent
        image: training.io/api:2.0
        ports:
          - containerPort: 80
        livenessProbe: 
          httpGet: 
            path: /api/v1/health-check/
            port: 80 
          initialDelaySeconds: 5 
          timeoutSeconds: 1 
          periodSeconds: 10 
          failureThreshold: 3
