apiVersion: v1
kind: Pod
metadata:
  name: api-pod
  labels:
    app: api
spec:
  containers:
  - name: training-api
    imagePullPolicy: IfNotPresent
    image: training.io/api:1.0
    ports:
      - containerPort: 80
      - containerPort: 443
    #
    # Readiness Check
    #
    # Perhaps the API, while technically healthy, is not yet "ready" to receive
    # traffic, as it may be downloading data, doing computations etc.
    readinessProbe:
      httpGet:
        path: /api/v1/readiness-check/
        port: 80
      initialDelaySeconds: 5
      periodSeconds: 5
    #
    # Health Check
    #
    livenessProbe:
      httpGet:
        path: /api/v1/health-check/
        port: 80
      initialDelaySeconds: 5
      timeoutSeconds: 1
      periodSeconds: 10
      failureThreshold: 3
