apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  selector:
    app: api
  ports:
  - name: http
    port: 80
    targetPort: app
  - name: https
    port: 443
    targetPort: app
  type: NodePort
